package lt.griaustinis.ytgame.assets;

public enum TextureKey {
    CHARACTER_STANDING_1,
    CHARACTER_WALKING_1,
    CHARACTER_WALKING_2,
    CHARACTER_WALKING_3,
    CHARACTER_WALKING_4,
    CHARACTER_WALKING_5,
    CHARACTER_WALKING_6
}
